[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
evm_version = 'paris'
optimizer = true
optimizer_runs = 200
gas_reports = ['*']
line_length = 80

[rpc_endpoints]
localhost = "${LOCALHOST}"
zkEVMPolygonMainnet = "${POLYGON_MAINNET_RPC_URL}"
zkEVMPolygonTestnet = "${POLYGON_TESTNET_RPC_URL}"

[etherscan]
etherscan = {key = "${POLYSCAN_API_KEY}", chain = 2442}
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
